# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    before_all do
      ensure_git_status_clean
    end


  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Chat.xcodeproj")
    build_app(scheme: "Chat-release")
    upload_to_testflight

    # Build is success
    git_commit(
      path: [
        "./Chat/Info.plist",
        "./Chat-tvOS/Info.plist",
        "./Chat-tvOSTests/Info.plist",
        "./ChatTests/Info.plist",
        "./Chat.xcodeproj/project.pbxproj"
      ],
      message: "iOS fastlane file changes"
    )
    push_to_git_remote

    add_git_tag
    push_git_tags
  end
end
